server:
  port: 19099
  max-http-header-size: 100000000
  tomcat:
    max-http-form-post-size: -1
    uri-encoding: UTF-8
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    name: self-manage
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/self_manage?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测0需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 102400000    # spring 文件上传限制
      max-request-size: 102400000 # Spring最大请求长度限制
  redis:
    database: 2
    host: 10.10.198.186
    port: 6379
    password: lab123456
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.nya.manage.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    com.nya.manage.mapper: debug